services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest_app_dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.dev
